# InfluxDB Service Stack

version: "3.7"

########################### NETWORKS
networks:
  # Stack-Only Networking
  internal:
    attachable: true
    driver: overlay
    ipam:
      config:
        - subnet: XXX.XXX.XXX.0/24
  # External Networking
  # All front-facing external services attach to this network!
  traefik_public:
    external: true

########################### SECRETS
#secrets:
#  secret_name_here:
#    external: true

########################### VOLUMES
#volumes:
#  volume_name_here:
#    external: true

########################### SERVICES
services:
  # All services / apps go below this line!

  # InfluxDB - Time-Series Database
  influxdb:
    image: influxdb:1.8-alpine
    deploy:
      labels:
        traefik.enable: "true"
        traefik.docker.network: "traefik_public"
        ## HTTP Routers
        traefik.http.services.influxdb.loadbalancer.server.port: "8086"
        traefik.http.routers.influxdb-rtr.rule: "Host(`influxdb.DOMAINNAME.TLD`)"
        ## HTTPS Services
        traefik.http.routers.influxdb-rtr.entrypoints: "https"
        traefik.http.routers.influxdb-rtr.tls.certresolver: "dns-cloudflare"
        # SSL Certificates
        traefik.http.routers.influxdb-rtr.tls.domains[0].main: "*.DOMAINNAME.TLD"
        traefik.http.routers.influxdb-rtr.tls.domains[0].sans: "DOMAINNAME.TLD"
        traefik.http.routers.influxdb-rtr.tls.domains[1].main: "*.DOMAINNAME.TLD"
        traefik.http.routers.influxdb-rtr.tls.domains[1].sans: "DOMAINNAME.TLD"
        ## HSTS Header Middleware
        traefik.http.middlewares.influxdb.headers.SSLRedirect: "true"
        traefik.http.middlewares.influxdb.headers.STSSeconds: "315360000"
        traefik.http.middlewares.influxdb.headers.browserXSSFilter: "true"
        traefik.http.middlewares.influxdb.headers.contentTypeNosniff: "true"
        traefik.http.middlewares.influxdb.headers.forceSTSHeader: "true"
        traefik.http.middlewares.influxdb.headers.SSLHost: ""
        traefik.http.middlewares.influxdb.headers.STSIncludeSubdomains: "true"
        traefik.http.middlewares.influxdb.headers.STSPreload: "true"
        traefik.http.middlewares.influxdb.headers.frameDeny: "true"
        ## Middleware Chains
        traefik.http.routers.influxdb-rtr.middlewares: "chain-authelia@file" # Authelia
      restart_policy:
        condition: any
    environment:
      # For environment variables, the format is INFLUXDB_$SECTION_$NAME.
      # All dashes (-) are replaced with underscores (_). 
      # If the variable isn't in a section, then omit that part.
      #
      #INFLUXDB_GRAPHITE_ENABLED: "false"
      INFLUXDB_DB: "" # Automatically initializes a database with the name of this environment variable.
      INFLUXDB_HTTP_AUTH_ENABLED: "true" # Enables authentication. Either this must be set or auth-enabled = true must be set within the configuration file for any authentication related options below to work.
      INFLUXDB_ADMIN_USER: "" # The name of the admin user to be created. If this is unset, no admin user is created.
      INFLUXDB_ADMIN_PASSWORD: "" # The password for the admin user configured with INFLUXDB_ADMIN_USER. If this is unset, a random password is generated and printed to standard out.
      INFLUXDB_USER: "" # The name of a user to be created with no privileges. If INFLUXDB_DB is set, this user will be granted read and write permissions for that database.
      INFLUXDB_USER_PASSWORD: "" # The password for the user configured with INFLUXDB_USER. If this is unset, a random password is generated and printed to standard out.
      INFLUXDB_READ_USER: "" # The name of a user to be created with read privileges on INFLUXDB_DB. If INFLUXDB_DB is not set, this user will have no granted permissions.
      INFLUXDB_READ_USER_PASSWORD: "" # The password for the user configured with INFLUXDB_READ_USER. If this is unset, a random password is generated and printed to standard out.
      INFLUXDB_WRITE_USER: "" # The name of a user to be created with write privileges on INFLUXDB_DB. If INFLUXDB_DB is not set, this user will have no granted permissions.
      INFLUXDB_WRITE_USER_PASSWORD: "" # The password for the user configured with INFLUXDB_WRITE_USER. If this is unset, a random password is generated and printed to standard out.
    networks:
      internal:
      traefik_public:
    ports:
      - target: 8086 # HTTP API port
        #published: 8086
        protocol: tcp
      - target: 8089 # UDP Port
        published: 8089
        protocol: udp
      #- target: 2003 # Graphite support, if it is enabled
      #  published: 2003
      #  protocol: tcp
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
      - type: bind
        source: /rootfs/influxdb/influxdb/_data/influxdb # Iknow,right?!
        target: /var/lib/influxdb
